# config/services.yaml
services:
    _defaults:
        autowire: true          # Automatically injects dependencies in your services.
        autoconfigure: true     # Automatically registers your services as commands, event subscribers, etc.

    Respinar\BxsliderBundle\:
        resource: ../src/
        exclude: ../src/{DependencyInjection,Session}